export const Data =[
    {
        name: "Nagaraj Pandith",
        username: "nagarajpandith",
        branch: "CSE",
        year: "3rd",
    },
    {
        name: "Anirudha kamath",
        username: "anirudha",
        branch: "ISE",
        year: "3rd",
    },
    {
        name: "abhishek",
        username: "abhishek",
        branch: "EC",
        year: "3rd",
    },
    {
        name: "Sangeetha Nayak",
        username: "sangeethanayak",
        branch: "ECE",
        year: "3rd",
    },
    {
        name: "ananth",
        username: "ak",
        branch: "ISE",
        year: "3rd",
    },
        name: "Ganesh Pai H",
        username: "ganeshpaih24",
        branch: "ISE",
        year: "3rd",
    },
        name: "Tanishka Rao",
        username: "tanishkarao16",
        branch: "CSE",
        year: "3rd",
    },
];
