export const Data = [{
    name: "Amogh",
    username: "akak",
    branch: "ai",
    year: "3rd",
}, 
{
        name: "Nagaraj Pandith",
        username: "nagarajpandith",
        branch: "CSE",
        year: "3rd",
    },
    {

        name: "Pradeep Rao K",
        username: "PradeepRaoK",
        branch: "CSE",
        year: "3rd",
},
{
        name: "Ardra Madhu",
        username: "ardramadhoo",
        branch: "CSE",
        year: "3rd",
    },
  {
        name: "suvith",
        username: "Htivus",
        branch: "CSE",
        year: "3rd",
    },
    {
        name:"Emmanuel Joshy",
        username:"Eman-69",
        branch:"CSE",
        year:"3rd",
    },
   {
        name: "Ananth Krishna",
        username: "ANANTHA1234842",
        branch: "ISE",
        year: "3rd",
    },
    {
        name: "parth1",
        username: "parth1",
        branch: "CSE",
        year: "3rd",
    },
    {
        name: "sanith shetty",
        username: "sanithshetty41",
        branch: "Ise",
        year: "3rd",
    },
    {
        name: "Sirish Pandit",
        username: "Sirish41",
        branch: "ISE",
        year: "3rd",
    },
    {
        name: "K Shravan",
        username: "dark-coder-144",
        branch: "CSE",
        year: "3rd",
    },
   {
        name: "Anirudha kamath",
        username: "anirudha",
        branch: "ISE",
        year: "3rd",
    },
    {
        name: "abhishek",
        username: "abhishek",
        branch: "EC",
        year: "3rd",
    },
    {
        name: "Sangeetha Nayak",
        username: "sangeethanayak",
        branch: "ECE",
        year: "3rd",
    },
    {
        name: "ananth",
        username: "ak",
        branch: "ISE",
        year: "3rd",
    },
    {
        name: "Ganesh Pai H",
        username: "ganeshpaih24",
        branch: "ISE",
        year: "3rd",
    },
    {
        name: "Tanishka Rao",
        username: "tanishkarao16",
        branch: "CSE",
        year: "3rd",
    },
];
